### ISSUE TITLE
main FAB rotates incorrectly

### ISSUE THREAD

**Issue by eehlers** [ajaydewari/FloatingActionButtonMenu#5]
there is a bug in the rotation of the main FAB.  the bug is not apparent in the current demo because the graphic (ic_toys) is symmetrical.  if you replace the graphic with one that is not symmetrical (for example, if you replace ic_toys with ic_mic) then you get the bug - the graphic ends up upside down after the animation.

![floating_action_button](https://user-images.githubusercontent.com/5637865/58240700-69092a80-7d43-11e9-9b21-adaf089e4cb0.png)

edit:  after running this in the debugger, it appears to me that showFABMenu() sometimes triggers the listener in closeFABMenu(), and vice versa.  so the rotation set by one of those functions may get superseded by the rotation set by the other, leaving the FAB in an incorrect position.  this is under API 28.

**Comment by Lecraver** [comment]
Yes ! I have the same problem here. Any solution ?

**Comment by ajay-dewari** [comment]
Issue is fixed and available in the master branch.
